# Generated by Django 3.0.1 on 2019-12-30 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Вид фотосъёмки')),
                ('poster_price', models.ImageField(upload_to='price_img/', verbose_name='Изображение фотосъёмки')),
                ('url', models.SlugField(unique=True, verbose_name='URL-привязка')),
            ],
            options={
                'verbose_name': 'Вид фотосъёмки',
                'verbose_name_plural': 'Виды фотосъёмок',
            },
        ),
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тарифа')),
                ('tariffs_description', models.TextField(verbose_name='Описание тарифа')),
                ('tariffs_price', models.CharField(max_length=100, verbose_name='Цена тарифа с указанием валюты')),
                ('price_tar', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='price.Price', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Price_Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание фотосъёмки для раздела "Прайс"')),
                ('price', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='price.Price', verbose_name='Вид фотосъёмки')),
            ],
            options={
                'verbose_name': 'Абзац описания фотосъёмки',
                'verbose_name_plural': 'Абзацы описания фотосъёмки',
            },
        ),
    ]
