# Generated by Django 3.0.1 on 2019-12-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Город')),
                ('poster_place', models.ImageField(upload_to='city_img/', verbose_name='Изображение')),
                ('url', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Место')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='places_img', verbose_name='Изображение')),
                ('maps', models.CharField(default='', max_length=300, verbose_name='Ссылка_на_расположение_на_карте')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='places.Sity', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
