# Generated by Django 3.0.1 on 2019-12-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='maps',
            field=models.CharField(default='', max_length=300, verbose_name='Ссылка на расположение на карте'),
        ),
    ]
