# Generated by Django 3.0.1 on 2020-01-03 02:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название альбома')),
                ('album_poster', models.ImageField(upload_to='svadebnaya_fotosessiya/', verbose_name='Обложка альбома')),
                ('date_album', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('url', models.SlugField(unique=True, verbose_name='URL-привязка')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='svadebnaya_fotosessiya/albums', verbose_name='Фотография')),
                ('album', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='svadebnaya_fotosessiya.Album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
