# Generated by Django 3.0.1 on 2020-02-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svadebnaya_fotosessiya', '0004_foto_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='width',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ширина'),
        ),
    ]
