# Generated by Django 3.0.1 on 2020-02-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svadebnaya_fotosessiya', '0010_auto_20200220_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='image',
            field=models.ImageField(upload_to='svadebnaya_fotosessiya/albums', verbose_name='Фотография хорошего качества'),
        ),
    ]
