# Generated by Django 3.0.1 on 2020-02-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svadebnaya_fotosessiya', '0012_auto_20200220_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='image',
            field=models.ImageField(blank=True, upload_to='svadebnaya_fotosessiya/albums', verbose_name='Фотография хорошего качества'),
        ),
    ]
