# Generated by Django 3.0.1 on 2020-02-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svadebnaya_fotosessiya', '0013_auto_20200220_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='image_low',
        ),
        migrations.AddField(
            model_name='foto',
            name='image_full',
            field=models.ImageField(blank=True, upload_to='svadebnaya_fotosessiya/albums/low', verbose_name='Фото с хорошим качеством'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='image',
            field=models.ImageField(upload_to='svadebnaya_fotosessiya/albums', verbose_name='Сжатая фотография'),
        ),
    ]
