# Generated by Django 3.0.1 on 2020-01-06 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_photosessiya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_birt',
            name='album',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='birthday_photosessiya.Album_birt', verbose_name='Альбом'),
        ),
    ]
