# Generated by Django 3.0.1 on 2020-01-07 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_photosessiya', '0003_auto_20200107_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album_birt',
            name='date_album',
        ),
    ]
