# Generated by Django 3.0.1 on 2020-02-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_photosessiya', '0005_auto_20200111_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto_birt',
            name='width',
            field=models.CharField(default='', max_length=100, verbose_name='Ширина 100%'),
        ),
    ]
