# Generated by Django 3.0.1 on 2020-02-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_photosessiya', '0006_foto_birt_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_birt',
            name='width',
            field=models.CharField(default='None', max_length=100, verbose_name='Ширина 100%'),
        ),
    ]
