# Generated by Django 3.0.1 on 2020-02-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_photosessiya', '0008_auto_20200215_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_birt',
            name='width',
            field=models.CharField(blank=True, default='стандарт', max_length=100, verbose_name='Ширина'),
        ),
    ]
