# Generated by Django 3.0.1 on 2020-02-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_photosessiya', '0011_auto_20200220_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_birt',
            name='image',
            field=models.ImageField(blank=True, upload_to='birthday_photosessiya/albums', verbose_name='Фотография хорошего качества'),
        ),
        migrations.AlterField(
            model_name='foto_birt',
            name='image_low',
            field=models.ImageField(default=models.ImageField(blank=True, upload_to='birthday_photosessiya/albums', verbose_name='Фотография хорошего качества'), upload_to='birthday_photosessiya/albums/low', verbose_name='Сжатая фотография'),
        ),
    ]
