# Generated by Django 3.0.1 on 2020-02-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_photosessiya', '0012_auto_20200220_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_birt',
            name='image_low',
            field=models.ImageField(default='#', upload_to='birthday_photosessiya/albums/low', verbose_name='Сжатая фотография'),
        ),
    ]
