# Generated by Django 3.0.1 on 2020-02-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_photosessiya', '0014_auto_20200222_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_birt',
            name='width',
            field=models.CharField(blank=True, max_length=15, verbose_name='Ширина'),
        ),
    ]
