# Generated by Django 3.0.1 on 2020-02-22 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_photosessiya', '0015_auto_20200222_0216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto_birt',
            options={'ordering': ('pk',), 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
