# Generated by Django 3.0.1 on 2020-01-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotoset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Свадебная фотосъёмка', max_length=100, verbose_name='Вид фотосъёмки')),
                ('poster_fotoset', models.ImageField(upload_to='fotoset_img/', verbose_name='Обложка Свадебной фотосъёмки')),
                ('name1', models.CharField(default='ИНДИВИДУАЛЬНАЯ ФОТОСЪЕМКА', max_length=100, verbose_name='Вид фотосъёмки')),
                ('poster_fotoset1', models.ImageField(upload_to='fotoset_img/', verbose_name='Обложка Индивидуальной фотосъёмки')),
                ('name2', models.CharField(default='СЕМЕЙНАЯ ФОТОСЪЕМКА', max_length=100, verbose_name='Вид фотосъёмки')),
                ('poster_fotoset2', models.ImageField(upload_to='fotoset_img/', verbose_name='Обложка Семейной фотосъёмки')),
                ('name3', models.CharField(default='ДЕТСКАЯ ФОТОСЪЕМКА', max_length=100, verbose_name='Вид фотосъёмки')),
                ('poster_fotoset3', models.ImageField(upload_to='fotoset_img/', verbose_name='Обложка Детской фотосъёмки')),
                ('name4', models.CharField(default='НОВОГОДНЯЯ ФОТОСЪЕМКА', max_length=100, verbose_name='Вид фотосъёмки')),
                ('poster_fotoset4', models.ImageField(upload_to='fotoset_img/', verbose_name='Обложка Новогодней фотосъёмки')),
                ('name5', models.CharField(default='ДЕНЬ РОЖДЕНИЯ', max_length=100, verbose_name='Вид фотосъёмки')),
                ('poster_fotoset5', models.ImageField(upload_to='fotoset_img/', verbose_name='Обложка фотосъёмки Дня рождения')),
                ('name6', models.CharField(default='LOVE STORY', max_length=100, verbose_name='Вид фотосъёмки')),
                ('poster_fotoset6', models.ImageField(upload_to='fotoset_img/', verbose_name='Обложка фотосъёмки LOVE STORY')),
            ],
            options={
                'verbose_name': 'Страничка Альбомы',
                'verbose_name_plural': 'Страничка Альбомы',
            },
        ),
    ]
