# Generated by Django 3.0.1 on 2020-01-03 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotoset',
            options={'verbose_name': 'Страничка "фотосессии"', 'verbose_name_plural': 'Страничка "фотосессии"'},
        ),
    ]
