# Generated by Django 3.0.1 on 2020-01-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums1', '0003_auto_20200104_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoset',
            name='name1',
            field=models.CharField(default='LOVE STORY', max_length=100, verbose_name='Вид фотосъёмки'),
        ),
        migrations.AlterField(
            model_name='fotoset',
            name='name4',
            field=models.CharField(default='ИНДИВИДУАЛЬНАЯ ФОТОСЪЕМКА', max_length=100, verbose_name='Вид фотосъёмки'),
        ),
        migrations.AlterField(
            model_name='fotoset',
            name='name6',
            field=models.CharField(default='НОВОГОДНЯЯ ФОТОСЪЕМКА', max_length=100, verbose_name='Вид фотосъёмки'),
        ),
        migrations.AlterField(
            model_name='fotoset',
            name='poster_fotoset1',
            field=models.ImageField(upload_to='fotoset_img/', verbose_name='Обложка фотосъёмки LOVE STORY'),
        ),
        migrations.AlterField(
            model_name='fotoset',
            name='poster_fotoset4',
            field=models.ImageField(upload_to='fotoset_img/', verbose_name='Обложка Индивидуальной фотосъёмки'),
        ),
        migrations.AlterField(
            model_name='fotoset',
            name='poster_fotoset6',
            field=models.ImageField(upload_to='fotoset_img/', verbose_name='Обложка Новогодней фотосъёмки'),
        ),
    ]
