# Generated by Django 3.0.1 on 2020-01-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums1', '0004_auto_20200107_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoset',
            name='name',
            field=models.CharField(default='СВАДЕБНАЯ ФОТОСЪЁМКА', max_length=100, verbose_name='Вид фотосъёмки'),
        ),
        migrations.AlterField(
            model_name='fotoset',
            name='name2',
            field=models.CharField(default='СЕМЕЙНАЯ ФОТОСЪЁМКА', max_length=100, verbose_name='Вид фотосъёмки'),
        ),
        migrations.AlterField(
            model_name='fotoset',
            name='name3',
            field=models.CharField(default='ДЕТСКАЯ ФОТОСЪЁМКА', max_length=100, verbose_name='Вид фотосъёмки'),
        ),
        migrations.AlterField(
            model_name='fotoset',
            name='name4',
            field=models.CharField(default='ИНДИВИДУАЛЬНАЯ ФОТОСЪЁМКА', max_length=100, verbose_name='Вид фотосъёмки'),
        ),
        migrations.AlterField(
            model_name='fotoset',
            name='name6',
            field=models.CharField(default='НОВОГОДНЯЯ ФОТОСЪЁМКА', max_length=100, verbose_name='Вид фотосъёмки'),
        ),
    ]
