# Generated by Django 3.0.1 on 2020-01-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head1', models.CharField(default='Популярные виды фотосессий', max_length=150, verbose_name='Заголовок для видов фотосессий')),
                ('head2', models.CharField(default='Такой-то альбом', max_length=150, verbose_name='Заголовок для слайдера')),
            ],
            options={
                'verbose_name': 'Заголовки на главной',
                'verbose_name_plural': 'Заголовки на главной',
            },
        ),
        migrations.CreateModel(
            name='Slider_down',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_sd', models.CharField(max_length=100, verbose_name='Очень короткое описание')),
                ('image_sd', models.ImageField(upload_to='secons_slider', verbose_name='Изображение для слайдера внизу')),
            ],
            options={
                'verbose_name': 'Изображение для второго слайдера',
                'verbose_name_plural': 'Изображения для второго слайдера',
            },
        ),
        migrations.CreateModel(
            name='Slider_head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Очень короткое описание')),
                ('image', models.ImageField(upload_to='main_slider', verbose_name='Изображение для слайдера вверху')),
            ],
            options={
                'verbose_name': 'Изображение для слайдера вверху страницы',
                'verbose_name_plural': 'Изображения для слайдера вверху страницы',
            },
        ),
    ]
