# Generated by Django 3.0.1 on 2020-01-07 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider_down',
            name='head2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Headers', verbose_name=''),
        ),
        migrations.AddField(
            model_name='slider_head',
            name='head1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Headers', verbose_name=''),
        ),
    ]
