# Generated by Django 3.0.2 on 2020-01-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200107_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='headers',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
