# Generated by Django 3.0.1 on 2020-01-05 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя автора отзыва')),
                ('avatar', models.ImageField(upload_to='reviews_autor', verbose_name='Аватар автора отзыва')),
                ('social_url', models.CharField(max_length=250, verbose_name='Ссылка на страничку в соц. сетях автора')),
                ('proof_url', models.CharField(max_length=250, verbose_name='Ссылка на сам отзыв в группе')),
            ],
            options={
                'verbose_name': 'Автор отзыва',
                'verbose_name_plural': 'Авторы отзывов',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_foto_rev', models.TextField(max_length=50, verbose_name='Очень короткое описание фото')),
                ('image', models.ImageField(upload_to='reviews_images', verbose_name='Фото к отзыву')),
                ('autor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reviews.Autor', verbose_name='Автор отзыва')),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Абзац отзыва')),
                ('autor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reviews.Autor', verbose_name='Автор отзыва')),
            ],
            options={
                'verbose_name': 'Абзац отзыва',
                'verbose_name_plural': 'Абзацы отзыва',
            },
        ),
    ]
