# Generated by Django 3.0.1 on 2020-01-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'verbose_name': 'Фотография к отзыву', 'verbose_name_plural': 'Фотографии к отзыву'},
        ),
    ]
