# Generated by Django 3.0.1 on 2020-01-07 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individualnaya_photosessiya', '0002_auto_20200103_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album_ind',
            name='date_album',
        ),
    ]
