# Generated by Django 3.0.1 on 2020-02-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualnaya_photosessiya', '0007_auto_20200220_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto_ind',
            name='image_low',
        ),
        migrations.AddField(
            model_name='foto_ind',
            name='image_full',
            field=models.ImageField(blank=True, upload_to='individualnaya_fotosessiya/albums/low', verbose_name='Фото с хорошим качеством'),
        ),
        migrations.AlterField(
            model_name='album_ind',
            name='album_poster',
            field=models.ImageField(upload_to='individualnaya_fotosessiya/', verbose_name='Обложка альбома'),
        ),
        migrations.AlterField(
            model_name='foto_ind',
            name='image',
            field=models.ImageField(upload_to='individualnaya_fotosessiya/albums', verbose_name='Сжатая фотография'),
        ),
    ]
