# Generated by Django 3.0.1 on 2020-01-07 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novogodnyaya_photosessiya', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album_nov',
            name='date_album',
        ),
    ]
