# Generated by Django 3.0.1 on 2019-12-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('avatar', models.ImageField(upload_to='about_img/', verbose_name='Изображение')),
                ('second_title', models.CharField(max_length=150, verbose_name='Заголовок подраздела')),
            ],
            options={
                'verbose_name': 'Обо мне',
                'verbose_name_plural': 'Обо мне',
            },
        ),
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_description', models.TextField(verbose_name='Абзац основного раздела')),
            ],
        ),
        migrations.CreateModel(
            name='Desc_second',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_description', models.TextField(verbose_name='Абзац дополнительного раздела')),
            ],
        ),
    ]
