# Generated by Django 3.0.1 on 2019-12-29 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desc',
            options={'verbose_name': 'Абзац основного раздела', 'verbose_name_plural': 'Абзацы основного раздела'},
        ),
        migrations.AlterModelOptions(
            name='desc_second',
            options={'verbose_name': 'Абзац дополнительного раздела', 'verbose_name_plural': 'Абзацы дополнительного раздела'},
        ),
        migrations.AddField(
            model_name='desc',
            name='about',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aboutMe.About', verbose_name='к заголовку'),
        ),
        migrations.AddField(
            model_name='desc_second',
            name='about_sec',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aboutMe.About', verbose_name='к заголовку'),
        ),
    ]
