# Generated by Django 3.0.2 on 2020-01-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe', '0003_about_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='second_title',
        ),
        migrations.DeleteModel(
            name='Desc_second',
        ),
    ]
