# Generated by Django 3.0.1 on 2020-02-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detskaya_photosessiya', '0008_auto_20200221_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_det',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='detskaya_photosessiya/albums', verbose_name='Фотография хорошего качества'),
        ),
        migrations.AlterField(
            model_name='foto_det',
            name='image_low',
            field=models.ImageField(upload_to='detskaya_photosessiya/albums/low', verbose_name='Сжатая фотография'),
        ),
    ]
