# Generated by Django 3.0.1 on 2020-02-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detskaya_photosessiya', '0012_auto_20200221_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_det',
            name='image',
            field=models.ImageField(upload_to='detskaya_photosessiya/albums', verbose_name='Сжатая фотография'),
        ),
        migrations.AlterField(
            model_name='foto_det',
            name='image_full',
            field=models.ImageField(blank=True, upload_to='detskaya_photosessiya/albums/low', verbose_name='Фото с хорошим качеством'),
        ),
    ]
